export type AOEProfile = {
    steam_id: string;
    profile_id: number;
    rank: number;
    rating: number;
    highest_rating: number;
    previous_rating: number;
    country_code: string;
    name: string;
    known_name: null;
    avatar: string;
    avatarfull: string;
    avatarmedium: string;
    num_games: number;
    streak: number;
    num_wins: number;
    win_percent: number;
    rating24h: number;
    games24h: number;
    wins24h: number;
    last_match: number;
};

export type AOEMatch = {
    id: number;
    steamLobbyId: number;
    appId: number;
    name: string;
    numPlayers: number;
    numSlots: number;
    status: string;
    full: boolean;
    active: boolean;
    cheats: boolean;
    fullTechTree: boolean;
    gameType: string;
    gameTypeId: number;
    hasPassword: boolean;
    hidden: boolean;
    location: string;
    lockSpeed: boolean;
    lockTeams: boolean;
    mapSize: string;
    pop: number;
    ranked: boolean;
    ratingType: number;
    resources: string;
    server: string;
    sharedExploration: boolean;
    speed: string;
    startingAge: string;
    turbo: boolean;
    victory: string;
    visibility: string;
    numSpectators: number;
    started: number;
    lastSeen: number;
    players: AOEPlayer[];
};

export type AOEPlayer = {
    steamId: number;
    profileId: number;
    slot: number;
    slotType: number;
    name: string;
    avatar: string;
    avatarfull: string;
    avatarmedium: string;
    countryCode: string;
    rating: number;
    color: number;
    team: number;
    civ: number;
    civName: string;
};

export type AOEHistoryMatch = {
    match_id: string;
    lobby_id: null;
    match_uuid: string;
    version: string;
    name: string;
    num_players: number;
    num_slots: number;
    average_rating: null;
    cheats: boolean;
    full_tech_tree: boolean;
    ending_age: number;
    expansion: null;
    game_type: number;
    has_custom_content: null;
    has_password: boolean;
    lock_speed: boolean;
    lock_teams: boolean;
    map_size: number;
    map_type: number;
    pop: number;
    ranked: boolean;
    leaderboard_id: number;
    rating_type: number;
    resources: number;
    rms: null;
    scenario: null;
    server: string;
    shared_exploration: boolean;
    speed: number;
    starting_age: number;
    team_together: boolean;
    team_positions: boolean;
    treaty_length: number;
    turbo: boolean;
    victory: number;
    victory_time: number;
    visibility: number;
    opened: number;
    started: number;
    finished: number;
    players: AOEHistoryMatchPlayer[];
};

export type AOEHistoryMatchPlayer = {
    profile_id: number;
    steam_id: string;
    name: string;
    clan: null;
    country: string;
    slot: number;
    slot_type: number;
    rating: number;
    rating_change: null;
    games: null;
    wins: null;
    streak: null;
    drops: null;
    color: number;
    team: number;
    civ: number;
    won: boolean;
};
