export type AOEProfile = {
    steam_id: string;
    profile_id: number;
    rank: number;
    rating: number;
    highest_rating: number;
    previous_rating: number;
    country_code: string;
    name: string;
    known_name: null;
    avatar: string;
    avatarfull: string;
    avatarmedium: string;
    num_games: number;
    streak: number;
    num_wins: number;
    win_percent: number;
    rating24h: number;
    games24h: number;
    wins24h: number;
    last_match: number;
};

export type AOEMatch = {
    id: number;
    steamLobbyId: number;
    appId: number;
    name: string;
    numPlayers: number;
    numSlots: number;
    status: string;
    full: boolean;
    active: boolean;
    cheats: false;
    fullTechTree: boolean;
    gameType: string;
    gameTypeId: number;
    hasPassword: boolean;
    hidden: boolean;
    location: string;
    lockSpeed: boolean;
    lockTeams: boolean;
    mapSize: string;
    pop: number;
    ranked: boolean;
    ratingType: number;
    resources: string;
    server: string;
    sharedExploration: boolean;
    speed: string;
    startingAge: string;
    turbo: boolean;
    victory: string;
    visibility: string;
    numSpectators: number;
    started: number;
    lastSeen: number;
    players: AOEPlayer[];
};

export type AOEPlayer = {
    steamId: number;
    profileId: number;
    slot: number;
    slotType: number;
    name: string;
    avatar: string;
    avatarfull: string;
    avatarmedium: string;
    countryCode: string;
    rating: number;
    color: number;
    team: number;
    civ: number;
    civName: string;
};
