export enum AGES {
    Standard = 0,
    DarkAge = 2,
    FeudalAge = 3,
    CastleAge = 4,
    ImperialAge = 5,
    PostImperialAge = 6,
}

export enum CIVILIZATIONS {
    Aztecs = 0,
    Berbers = 1,
    Britons = 2,
    Bulgarians = 3,
    Burgundians = 4,
    Burmese = 5,
    Byzantines = 6,
    Celts = 7,
    Chinese = 8,
    Cumans = 9,
    Ethiopians = 10,
    Franks = 11,
    Goths = 12,
    Huns = 13,
    Incas = 14,
    Indians = 15,
    Italians = 16,
    Japanese = 17,
    Khmer = 18,
    Koreans = 19,
    Lithuanians = 20,
    Magyars = 21,
    Malay = 22,
    Malians = 23,
    Mayans = 24,
    Mongols = 25,
    Persians = 26,
    Portuguese = 27,
    Saracens = 28,
    Sicilians = 29,
    Slavs = 30,
    Spanish = 31,
    Tatars = 32,
    Teutons = 33,
    Turks = 34,
    Vietnamese = 35,
    Vikings = 36,
}

export enum GAME_TYPES {
    RandomMap = 0,
    Regicide = 1,
    DeathMatch = 2,
    Scenario = 3,
    KingOfTheHill = 6,
    WonderRace = 7,
    DefendTheWonder = 8,
    TurboRandomMap = 9,
    CaptureTheRelic = 10,
    SuddenDeath = 11,
    BattleRoyale = 12,
    EmpireWars = 13,
}
export enum LEADERBOARDS {
    Unranked = 0,
    DeathMatch1v1 = 1,
    TeamDeathMatch = 2,
    RandomMap1v1 = 3,
    TeamRandomMap = 4,
}

export enum MAP_SIZES {
    Tiny = 0,
    Small = 1,
    Medium = 2,
    Normal = 3,
    Large = 4,
    Giant = 5,
    Ludicrous = 6,
}

export enum MAP_TYPES {
    Arabia = 9,
    Archipelago = 10,
    Baltic = 11,
    BlackForest = 12,
    Coastal = 13,
    Continental = 14,
    CraterLake = 15,
    Fortress = 16,
    GoldRush = 17,
    Highland = 18,
    Islands = 19,
    Mediterranean = 20,
    Migration = 21,
    Rivers = 22,
    TeamIslands = 23,
    FullRandom = 24,
    Scandinavia = 25,
    Mongolia = 26,
    Yucatan = 27,
    SaltMarsh = 28,
    Arena = 29,
    Oasis = 31,
    GhostLake = 32,
    Nomad = 33,
    Iberia = 49,
    Britain = 50,
    Mideast = 51,
    Texas = 52,
    Italy = 53,
    CentralAmerica = 54,
    France = 55,
    NorseLands = 56,
    SeaOfJapan = 57,
    Byzantium = 58,
    Custom = 59,
    RandomLandMap = 60,
    RandomRealWorldMap = 62,
    BlindRandom = 63,
    RandomSpecialMap = 65,
    RandomSpecialMap2 = 66,
    Acropolis = 67,
    Budapest = 68,
    Cenotes = 69,
    CityOfLakes = 70,
    GoldenPit = 71,
    Hideout = 72,
    HillFort = 73,
    Lombardia = 74,
    Steppe = 75,
    Valley = 76,
    MegaRandom = 77,
    Hamburger = 78,
    CtRRandom = 79,
    CtRMonsoon = 80,
    CtRPyramidDescent = 81,
    CtRSpiral = 82,
    Kilimanjaro = 83,
    MountainPass = 84,
    NileDelta = 85,
    Serengeti = 86,
    Socotra = 87,
    Amazon = 88,
    China = 89,
    HornOfAfrica = 90,
    India = 91,
    Madagascar = 92,
    WestAfrica = 93,
    Bohemia = 94,
    Earth = 95,
    Canyons = 96,
    EnemyArchipelago = 97,
    EnemyIslands = 98,
    FarOut = 99,
    FrontLine = 100,
    InnerCircle = 101,
    Motherland = 102,
    OpenPlains = 103,
    RingOfWater = 104,
    Snakepit = 105,
    TheEye = 106,
    Australia = 107,
    Indochina = 108,
    Indonesia = 109,
    StraitOfMalacca = 110,
    Philippines = 111,
    BogIslands = 112,
    MangroveJungle = 113,
    PacificIslands = 114,
    Sandbank = 115,
    WaterNomad = 116,
    JungleIslands = 117,
    HolyLine = 118,
    BorderStones = 119,
    YinYang = 120,
    JungleLanes = 121,
    AlpineLakes = 122,
    Bogland = 123,
    MountainRidge = 124,
    Ravines = 125,
    WolfHill = 126,
    Antarctica = 132,
    CustomMapPool = 137,
    GoldenSwamp = 139,
    FourLakes = 140,
    LandNomad = 141,
    BRBattleOnIce = 142,
    BRElDorado = 143,
    BRFallOfAxum = 144,
    BRFallOfRome = 145,
    BRMajapahitEmpire = 146,
    AmazonTunnel = 147,
    CoastalForest = 148,
    AfricanClearing = 149,
    Atacama = 150,
    SeizeTheMountain = 151,
}

export enum RATING_TYPES {
    Unranked = 0,
    DeathMatch1v1 = 1,
    RandomMap1v1 = 2,
    TeamDeathMatch = 3,
    TeamRandomMap = 4,
    RandomMapQuickPlay1v1 = 5,
    TeamRandomMapQuickPlay = 6,
    EmpireWarsQuickPlay1v1 = 7,
    TeamEmpireWarsQuickPlay = 8,
    BattleRoyaleQuickPlay = 9,
}

export enum RESOURCES {
    Standard = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    UltraHigh = 4,
    Infinite = 5,
    Random = 6,
}

export enum SPEEDS {
    Slow = 0,
    Casual = 1,
    Normal = 2,
    Fast = 3,
}

export enum VICTORIES {
    Conquest = 1,
    TimeLimit = 7,
    Score = 8,
    Standard = 9,
    LastManStanding = 11,
}

export enum VISIBILITIES {
    Normal = 0,
    Explored = 1,
    AllVisible = 2,
}
